### ISSUE TITLE
Diagrama de Estados

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#10]
## Descrição da Issue
Criação do diagrama  de Estados
## Tasks:
- [x] Esta bem documentado 
- [ ] As imagens condizem com o que e proposto para o projeto

## Critérios de Aceitação:
- [x] Precisa de 5 revisores

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.
