### ISSUE TITLE
Diagrama de Implantação

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#12]
## Descrição da Issue
Criação do diagrama  de Implantação
## Tasks:
- [ ] Esta bem documentado 
- [ ] As imagens condizem com o que e proposto para o projeto

## Critérios de Aceitação:
- [ ] Precisa de 5 revisores

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.

**Comment by heitormsb** [comment]
Link diagrama (visualização):
https://lucid.app/lucidchart/598611f0-f093-44fe-9c61-4975a724ed7b/edit?viewport_loc=-2423%2C-1090%2C3072%2C1601%2C0_0&invitationId=inv_2810d196-0dba-4355-afed-fefe428cc4b8
