### ISSUE TITLE
Diagrama  de Classes

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#13]
## Descrição da Issue
Criação do diagrama  de Classes
## Tasks:
- [x] Esta bem documentado 
- [x] As imagens condizem com o que e proposto para o projeto

## Critérios de Aceitação:
- [x] Precisa de 4 revisores

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.

**Comment by klmurussi** [comment]
link para onde o diagrama está sendo feito (apenas visualização):
https://lucid.app/lucidchart/a53dd78b-4cc5-443a-9448-48a2df2695d2/edit?viewport_loc=-197%2C-21%2C2922%2C1261%2CHWEp-vi-RSFO&invitationId=inv_70e52ed6-fa8c-457d-ac8d-1d17809f36ae
