### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#14]
## Descrição da Issue
Criação do diagrama  de Componentes
## Tasks:
- [ ] Esta bem documentado 
- [ ] As imagens condizem com o que e proposto para o projeto

## Critérios de Aceitação:
- [ ] Precisa de 5 revisores

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.

**Comment by heitormsb** [comment]
Link diagrama (visualização):
https://lucid.app/lucidchart/91afaac8-0b3f-412f-afa5-fa915f43e5c2/edit?viewport_loc=-1131%2C-325%2C5123%2C2670%2C0_0&invitationId=inv_f41c5f3f-973f-4d5d-894d-5b8b99a4f796
