### ISSUE TITLE
Diagrama  de Pacotes

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#15]
## Descrição da Issue
Criação do diagrama  de Pacotes
## Tasks:
- [ ] Esta bem documentado 
- [ ] As imagens condizem com o que e proposto para o projeto

## Critérios de Aceitação:
- [ ] Precisa de 5 revisores

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.

**Comment by heitormsb** [comment]
Link diagrama (visualização):
https://lucid.app/lucidchart/b0da7e87-85f6-4303-9ea4-6dec3b3061d2/edit?viewport_loc=-1911%2C607%2C3359%2C1601%2C0_0&invitationId=inv_a7fd27d8-7a1e-4c20-9620-6f94fdabffe4
