### ISSUE TITLE
2° entrega de arquitetura, incluindo diagramas estáticos e dinâmicos.

### ISSUE THREAD

**Issue by Ericklevy** [UnBArqDsw2023-1/2023.1_G3_ProjetoMercadoLivre#16]
## Descrição da Issue
Completar os documentos de diagramas tanto estáticos como dinâmicos para 2° entrega de Arquitetura e desenho de Software

## Diagrama estáticos 
- [x] Diagrama de Classes
- [x] Diagrama de Componentes
- [x] Diagrama de Implantação
- [x] Diagrama de Pacotes

## Diagrama dinâmicos
- [x] Diagrama de Atividades
- [x] Diagrama de Colaboração/Comunicação
- [x] Diagrama de Estados
- [x] Diagrama de Sequencia

## Extra
- [x] #23
- [ ] Adicionar atas das reuniões da Entrega 2
- [x] #24

## Critérios de Aceitação:
- [ ] finalizar todos os documentos corrigidos e se preparar para apresentação de arquitetura

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## Milestone
A issue deve ser atribuída ao Milestone (sprint) correspondente previsto para sua execução.
